# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160818_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_com',
        ),
    ]
