# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160825_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_com',
            new_name='author',
        ),
    ]
